import { stats, loadStats, changeStats, submitStats, swapStats } from "./save.js";
document.getElementById("setup").addEventListener("click", changeStats);
document.getElementById("calculator").addEventListener("click", submitStats);
document.getElementById("swap").addEventListener("click", swapStats);
document.getElementById("fileASave").addEventListener("click", fileASave);
document.getElementById("fileBSave").addEventListener("click", fileBSave);
document.getElementById("fileCSave").addEventListener("click", fileCSave);
document.getElementById("fileDSave").addEventListener("click", fileDSave);
document.getElementById("fileESave").addEventListener("click", fileESave);
document.getElementById("fileALoad").addEventListener("click", fileALoad);
document.getElementById("fileBLoad").addEventListener("click", fileBLoad);
document.getElementById("fileCLoad").addEventListener("click", fileCLoad);
document.getElementById("fileDLoad").addEventListener("click", fileDLoad);
document.getElementById("fileELoad").addEventListener("click", fileELoad);
let fileAName = "";
let fileBName = "";
let fileCName = "";
let fileDName = "";
let fileEName = "";

function populateStats() {
    document.getElementById("hp").value = stats.hp;
    document.getElementById("hp").disabled = true;
    document.getElementById("maxHp").value = stats.maxHp;
    document.getElementById("maxHp").disabled = true;
    document.getElementById("tempHp").value = stats.tempHp;
    document.getElementById("tempHp").disabled = true;
    document.getElementById("ep").value = stats.ep;
    document.getElementById("ep").disabled = true;
    document.getElementById("maxEp").value = stats.maxEp;
    document.getElementById("maxEp").disabled = true;
    document.getElementById("tempEp").value = stats.tempEp;
    document.getElementById("tempEp").disabled = true;
    document.getElementById("stamina").value = stats.stamina;
    document.getElementById("stamina").disabled = true;
    document.getElementById("maxStamina").value = stats.maxStamina;
    document.getElementById("maxStamina").disabled = true;
    document.getElementById("tempStamina").value = stats.tempStamina;
    document.getElementById("tempStamina").disabled = true;
    document.getElementById("mana").value = stats.mana;
    document.getElementById("mana").disabled = true;
    document.getElementById("maxMana").value = stats.maxMana;
    document.getElementById("maxMana").disabled = true;
    document.getElementById("tempMana").value = stats.tempMana;
    document.getElementById("tempMana").disabled = true;

    fileAName = localStorage.getItem("fileAName");
    fileBName = localStorage.getItem("fileBName");
    fileCName = localStorage.getItem("fileCName");
    fileDName = localStorage.getItem("fileDName");
    fileEName = localStorage.getItem("fileEName");
    document.getElementById("fileAName").value = fileAName;
    document.getElementById("fileBName").value = fileBName;
    document.getElementById("fileCName").value = fileCName;
    document.getElementById("fileDName").value = fileDName;
    document.getElementById("fileEName").value = fileEName;
}

function fileASave() {
    localStorage.setItem("hpA", stats.hp);
    localStorage.setItem("maxHpA", stats.maxHp);
    localStorage.setItem("tempHpA", stats.tempHp);
    localStorage.setItem("epA", stats.ep);
    localStorage.setItem("maxEpA", stats.maxEp);
    localStorage.setItem("tempEpA", stats.tempEp);
    localStorage.setItem("staminaA", stats.stamina);
    localStorage.setItem("maxStaminaA", stats.maxStamina);
    localStorage.setItem("tempStaminaA", stats.tempStamina);
    localStorage.setItem("manaA", stats.mana);
    localStorage.setItem("maxManaA", stats.maxMana);
    localStorage.setItem("tempManaA", stats.tempMana);
    localStorage.setItem("blockA", stats.block);
    localStorage.setItem("wardA", stats.ward);
    localStorage.setItem("indomitableA", stats.indomitable);
    localStorage.setItem("resImpactA", stats.resImpact);
    localStorage.setItem("resFireA", stats.resFire);
    localStorage.setItem("resFrostA", stats.resFrost);
    localStorage.setItem("resStormA", stats.resStorm);
    localStorage.setItem("resAcidA", stats.resAcid);
    localStorage.setItem("resPoisonA", stats.resPoison);
    localStorage.setItem("resFluxA", stats.resFlux);
    localStorage.setItem("resChaosA", stats.resChaos);
    localStorage.setItem("resHolyA", stats.resHoly);
    localStorage.setItem("resUnholyA", stats.resUnholy);
    localStorage.setItem("braceBlockA", stats.braceBlock);
    localStorage.setItem("braceWardA", stats.braceWard);
    fileAName = document.getElementById("fileAName").value;
    fileBName = document.getElementById("fileBName").value;
    fileCName = document.getElementById("fileCName").value;
    fileDName = document.getElementById("fileDName").value;
    fileEName = document.getElementById("fileEName").value;
    localStorage.setItem("fileAName", fileAName);
    localStorage.setItem("fileBName", fileBName);
    localStorage.setItem("fileCName", fileCName);
    localStorage.setItem("fileDName", fileDName);
    localStorage.setItem("fileEName", fileEName);
}

function fileBSave() {
    localStorage.setItem("hpB", stats.hp);
    localStorage.setItem("maxHpB", stats.maxHp);
    localStorage.setItem("tempHpB", stats.tempHp);
    localStorage.setItem("epB", stats.ep);
    localStorage.setItem("maxEpB", stats.maxEp);
    localStorage.setItem("tempEpB", stats.tempEp);
    localStorage.setItem("staminaB", stats.stamina);
    localStorage.setItem("maxStaminaB", stats.maxStamina);
    localStorage.setItem("tempStaminaB", stats.tempStamina);
    localStorage.setItem("manaB", stats.mana);
    localStorage.setItem("maxManaB", stats.maxMana);
    localStorage.setItem("tempManaB", stats.tempMana);
    localStorage.setItem("blockB", stats.block);
    localStorage.setItem("wardB", stats.ward);
    localStorage.setItem("indomitableB", stats.indomitable);
    localStorage.setItem("resImpactB", stats.resImpact);
    localStorage.setItem("resFireB", stats.resFire);
    localStorage.setItem("resFrostB", stats.resFrost);
    localStorage.setItem("resStormB", stats.resStorm);
    localStorage.setItem("resAcidB", stats.resAcid);
    localStorage.setItem("resPoisonB", stats.resPoison);
    localStorage.setItem("resFluxB", stats.resFlux);
    localStorage.setItem("resChaosB", stats.resChaos);
    localStorage.setItem("resHolyB", stats.resHoly);
    localStorage.setItem("resUnholyB", stats.resUnholy);
    localStorage.setItem("braceBlockB", stats.braceBlock);
    localStorage.setItem("braceWardB", stats.braceWard);
    fileAName = document.getElementById("fileAName").value;
    fileBName = document.getElementById("fileBName").value;
    fileCName = document.getElementById("fileCName").value;
    fileDName = document.getElementById("fileDName").value;
    fileEName = document.getElementById("fileEName").value;
    localStorage.setItem("fileAName", fileAName);
    localStorage.setItem("fileBName", fileBName);
    localStorage.setItem("fileCName", fileCName);
    localStorage.setItem("fileDName", fileDName);
    localStorage.setItem("fileEName", fileEName);
}

function fileCSave() {
    localStorage.setItem("hpC", stats.hp);
    localStorage.setItem("maxHpC", stats.maxHp);
    localStorage.setItem("tempHpC", stats.tempHp);
    localStorage.setItem("epC", stats.ep);
    localStorage.setItem("maxEpC", stats.maxEp);
    localStorage.setItem("tempEpC", stats.tempEp);
    localStorage.setItem("staminaC", stats.stamina);
    localStorage.setItem("maxStaminaC", stats.maxStamina);
    localStorage.setItem("tempStaminaC", stats.tempStamina);
    localStorage.setItem("manaC", stats.mana);
    localStorage.setItem("maxManaC", stats.maxMana);
    localStorage.setItem("tempManaC", stats.tempMana);
    localStorage.setItem("blockC", stats.block);
    localStorage.setItem("wardC", stats.ward);
    localStorage.setItem("indomitableC", stats.indomitable);
    localStorage.setItem("resImpactC", stats.resImpact);
    localStorage.setItem("resFireC", stats.resFire);
    localStorage.setItem("resFrostC", stats.resFrost);
    localStorage.setItem("resStormC", stats.resStorm);
    localStorage.setItem("resAcidC", stats.resAcid);
    localStorage.setItem("resPoisonC", stats.resPoison);
    localStorage.setItem("resFluxC", stats.resFlux);
    localStorage.setItem("resChaosC", stats.resChaos);
    localStorage.setItem("resHolyC", stats.resHoly);
    localStorage.setItem("resUnholyC", stats.resUnholy);
    localStorage.setItem("braceBlockC", stats.braceBlock);
    localStorage.setItem("braceWardC", stats.braceWard);
    fileAName = document.getElementById("fileAName").value;
    fileBName = document.getElementById("fileBName").value;
    fileCName = document.getElementById("fileCName").value;
    fileDName = document.getElementById("fileDName").value;
    fileEName = document.getElementById("fileEName").value;
    localStorage.setItem("fileAName", fileAName);
    localStorage.setItem("fileBName", fileBName);
    localStorage.setItem("fileCName", fileCName);
    localStorage.setItem("fileDName", fileDName);
    localStorage.setItem("fileEName", fileEName);
}

function fileDSave() {
    localStorage.setItem("hpD", stats.hp);
    localStorage.setItem("maxHpD", stats.maxHp);
    localStorage.setItem("tempHpD", stats.tempHp);
    localStorage.setItem("epD", stats.ep);
    localStorage.setItem("maxEpD", stats.maxEp);
    localStorage.setItem("tempEpD", stats.tempEp);
    localStorage.setItem("staminaD", stats.stamina);
    localStorage.setItem("maxStaminaD", stats.maxStamina);
    localStorage.setItem("tempStaminaD", stats.tempStamina);
    localStorage.setItem("manaD", stats.mana);
    localStorage.setItem("maxManaD", stats.maxMana);
    localStorage.setItem("tempManaD", stats.tempMana);
    localStorage.setItem("blockD", stats.block);
    localStorage.setItem("wardD", stats.ward);
    localStorage.setItem("indomitableD", stats.indomitable);
    localStorage.setItem("resImpactD", stats.resImpact);
    localStorage.setItem("resFireD", stats.resFire);
    localStorage.setItem("resFrostD", stats.resFrost);
    localStorage.setItem("resStormD", stats.resStorm);
    localStorage.setItem("resAcidD", stats.resAcid);
    localStorage.setItem("resPoisonD", stats.resPoison);
    localStorage.setItem("resFluxD", stats.resFlux);
    localStorage.setItem("resChaosD", stats.resChaos);
    localStorage.setItem("resHolyD", stats.resHoly);
    localStorage.setItem("resUnholyD", stats.resUnholy);
    localStorage.setItem("braceBlockD", stats.braceBlock);
    localStorage.setItem("braceWardD", stats.braceWard);
    fileAName = document.getElementById("fileAName").value;
    fileBName = document.getElementById("fileBName").value;
    fileCName = document.getElementById("fileCName").value;
    fileDName = document.getElementById("fileDName").value;
    fileEName = document.getElementById("fileEName").value;
    localStorage.setItem("fileAName", fileAName);
    localStorage.setItem("fileBName", fileBName);
    localStorage.setItem("fileCName", fileCName);
    localStorage.setItem("fileDName", fileDName);
    localStorage.setItem("fileEName", fileEName);
}

function fileESave() {
    localStorage.setItem("hpE", stats.hp);
    localStorage.setItem("maxHpE", stats.maxHp);
    localStorage.setItem("tempHpE", stats.tempHp);
    localStorage.setItem("epE", stats.ep);
    localStorage.setItem("maxEpE", stats.maxEp);
    localStorage.setItem("tempEpE", stats.tempEp);
    localStorage.setItem("staminaE", stats.stamina);
    localStorage.setItem("maxStaminaE", stats.maxStamina);
    localStorage.setItem("tempStaminaE", stats.tempStamina);
    localStorage.setItem("manaE", stats.mana);
    localStorage.setItem("maxManaE", stats.maxMana);
    localStorage.setItem("tempManaE", stats.tempMana);
    localStorage.setItem("blockE", stats.block);
    localStorage.setItem("wardE", stats.ward);
    localStorage.setItem("indomitableE", stats.indomitable);
    localStorage.setItem("resImpactE", stats.resImpact);
    localStorage.setItem("resFireE", stats.resFire);
    localStorage.setItem("resFrostE", stats.resFrost);
    localStorage.setItem("resStormE", stats.resStorm);
    localStorage.setItem("resAcidE", stats.resAcid);
    localStorage.setItem("resPoisonE", stats.resPoison);
    localStorage.setItem("resFluxE", stats.resFlux);
    localStorage.setItem("resChaosE", stats.resChaos);
    localStorage.setItem("resHolyE", stats.resHoly);
    localStorage.setItem("resUnholyE", stats.resUnholy);
    localStorage.setItem("braceBlockE", stats.braceBlock);
    localStorage.setItem("braceWardE", stats.braceWard);
    fileAName = document.getElementById("fileAName").value;
    fileBName = document.getElementById("fileBName").value;
    fileCName = document.getElementById("fileCName").value;
    fileDName = document.getElementById("fileDName").value;
    fileEName = document.getElementById("fileEName").value;
    localStorage.setItem("fileAName", fileAName);
    localStorage.setItem("fileBName", fileBName);
    localStorage.setItem("fileCName", fileCName);
    localStorage.setItem("fileDName", fileDName);
    localStorage.setItem("fileEName", fileEName);
}

function fileALoad() {
    stats.hp = Number(localStorage.getItem("hpA"));
    stats.maxHp = Number(localStorage.getItem("maxHpA"));
    stats.tempHp = Number(localStorage.getItem("tempHpA"));
    stats.ep = Number(localStorage.getItem("epA"));
    stats.maxEp = Number(localStorage.getItem("maxEpA"));
    stats.tempEp = Number(localStorage.getItem("tempEpA"));
    stats.stamina = Number(localStorage.getItem("staminaA"));
    stats.maxStamina = Number(localStorage.getItem("maxStaminaA"));
    stats.tempStamina = Number(localStorage.getItem("tempStaminaA"));
    stats.mana = Number(localStorage.getItem("manaA"));
    stats.maxMana = Number(localStorage.getItem("maxManaA"));
    stats.tempMana = Number(localStorage.getItem("tempManaA"));
    stats.block = Number(localStorage.getItem("blockA"));
    stats.ward = Number(localStorage.getItem("wardA"));
    stats.indomitable = Number(localStorage.getItem("indomitableA"));
    stats.resImpact = Number(localStorage.getItem("resImpactA"));
    stats.resFire = Number(localStorage.getItem("resFireA"));
    stats.resFrost = Number(localStorage.getItem("resFrostA"));
    stats.resStorm = Number(localStorage.getItem("resStormA"));
    stats.resAcid = Number(localStorage.getItem("resAcidA"));
    stats.resPoison = Number(localStorage.getItem("resPoisonA"));
    stats.resFlux = Number(localStorage.getItem("resFluxA"));
    stats.resChaos = Number(localStorage.getItem("resChaosA"));
    stats.resHoly = Number(localStorage.getItem("resHolyA"));
    stats.resUnholy = Number(localStorage.getItem("resUnholyA"));
    stats.braceBlock = Number(localStorage.getItem("braceBlockA"));
    stats.braceWard = Number(localStorage.getItem("braceWardA"));
    populateStats();
}

function fileBLoad() {
    stats.hp = Number(localStorage.getItem("hpB"));
    stats.maxHp = Number(localStorage.getItem("maxHpB"));
    stats.tempHp = Number(localStorage.getItem("tempHpB"));
    stats.ep = Number(localStorage.getItem("epB"));
    stats.maxEp = Number(localStorage.getItem("maxEpB"));
    stats.tempEp = Number(localStorage.getItem("tempEpB"));
    stats.stamina = Number(localStorage.getItem("staminaB"));
    stats.maxStamina = Number(localStorage.getItem("maxStaminaB"));
    stats.tempStamina = Number(localStorage.getItem("tempStaminaB"));
    stats.mana = Number(localStorage.getItem("manaB"));
    stats.maxMana = Number(localStorage.getItem("maxManaB"));
    stats.tempMana = Number(localStorage.getItem("tempManaB"));
    stats.block = Number(localStorage.getItem("blockB"));
    stats.ward = Number(localStorage.getItem("wardB"));
    stats.indomitable = Number(localStorage.getItem("indomitableB"));
    stats.resImpact = Number(localStorage.getItem("resImpactB"));
    stats.resFire = Number(localStorage.getItem("resFireB"));
    stats.resFrost = Number(localStorage.getItem("resFrostB"));
    stats.resStorm = Number(localStorage.getItem("resStormB"));
    stats.resAcid = Number(localStorage.getItem("resAcidB"));
    stats.resPoison = Number(localStorage.getItem("resPoisonB"));
    stats.resFlux = Number(localStorage.getItem("resFluxB"));
    stats.resChaos = Number(localStorage.getItem("resChaosB"));
    stats.resHoly = Number(localStorage.getItem("resHolyB"));
    stats.resUnholy = Number(localStorage.getItem("resUnholyB"));
    stats.braceBlock = Number(localStorage.getItem("braceBlockB"));
    stats.braceWard = Number(localStorage.getItem("braceWardB"));
    populateStats();
}

function fileCLoad() {
    stats.hp = Number(localStorage.getItem("hpC"));
    stats.maxHp = Number(localStorage.getItem("maxHpC"));
    stats.tempHp = Number(localStorage.getItem("tempHpC"));
    stats.ep = Number(localStorage.getItem("epC"));
    stats.maxEp = Number(localStorage.getItem("maxEpC"));
    stats.tempEp = Number(localStorage.getItem("tempEpC"));
    stats.stamina = Number(localStorage.getItem("staminaC"));
    stats.maxStamina = Number(localStorage.getItem("maxStaminaC"));
    stats.tempStamina = Number(localStorage.getItem("tempStaminaC"));
    stats.mana = Number(localStorage.getItem("manaC"));
    stats.maxMana = Number(localStorage.getItem("maxManaC"));
    stats.tempMana = Number(localStorage.getItem("tempManaC"));
    stats.block = Number(localStorage.getItem("blockC"));
    stats.ward = Number(localStorage.getItem("wardC"));
    stats.indomitable = Number(localStorage.getItem("indomitableC"));
    stats.resImpact = Number(localStorage.getItem("resImpactC"));
    stats.resFire = Number(localStorage.getItem("resFireC"));
    stats.resFrost = Number(localStorage.getItem("resFrostC"));
    stats.resStorm = Number(localStorage.getItem("resStormC"));
    stats.resAcid = Number(localStorage.getItem("resAcidC"));
    stats.resPoison = Number(localStorage.getItem("resPoisonC"));
    stats.resFlux = Number(localStorage.getItem("resFluxC"));
    stats.resChaos = Number(localStorage.getItem("resChaosC"));
    stats.resHoly = Number(localStorage.getItem("resHolyC"));
    stats.resUnholy = Number(localStorage.getItem("resUnholyC"));
    stats.braceBlock = Number(localStorage.getItem("braceBlockC"));
    stats.braceWard = Number(localStorage.getItem("braceWardC"));
    populateStats();
}

function fileDLoad() {
    stats.hp = Number(localStorage.getItem("hpD"));
    stats.maxHp = Number(localStorage.getItem("maxHpD"));
    stats.tempHp = Number(localStorage.getItem("tempHpD"));
    stats.ep = Number(localStorage.getItem("epD"));
    stats.maxEp = Number(localStorage.getItem("maxEpD"));
    stats.tempEp = Number(localStorage.getItem("tempEpD"));
    stats.stamina = Number(localStorage.getItem("staminaD"));
    stats.maxStamina = Number(localStorage.getItem("maxStaminaD"));
    stats.tempStamina = Number(localStorage.getItem("tempStaminaD"));
    stats.mana = Number(localStorage.getItem("manaD"));
    stats.maxMana = Number(localStorage.getItem("maxManaD"));
    stats.tempMana = Number(localStorage.getItem("tempManaD"));
    stats.block = Number(localStorage.getItem("blockD"));
    stats.ward = Number(localStorage.getItem("wardD"));
    stats.indomitable = Number(localStorage.getItem("indomitableD"));
    stats.resImpact = Number(localStorage.getItem("resImpactD"));
    stats.resFire = Number(localStorage.getItem("resFireD"));
    stats.resFrost = Number(localStorage.getItem("resFrostD"));
    stats.resStorm = Number(localStorage.getItem("resStormD"));
    stats.resAcid = Number(localStorage.getItem("resAcidD"));
    stats.resPoison = Number(localStorage.getItem("resPoisonD"));
    stats.resFlux = Number(localStorage.getItem("resFluxD"));
    stats.resChaos = Number(localStorage.getItem("resChaosD"));
    stats.resHoly = Number(localStorage.getItem("resHolyD"));
    stats.resUnholy = Number(localStorage.getItem("resUnholyD"));
    stats.braceBlock = Number(localStorage.getItem("braceBlockD"));
    stats.braceWard = Number(localStorage.getItem("braceWardD"));
    populateStats();
}

function fileELoad() {
    stats.hp = Number(localStorage.getItem("hpE"));
    stats.maxHp = Number(localStorage.getItem("maxHpE"));
    stats.tempHp = Number(localStorage.getItem("tempHpE"));
    stats.ep = Number(localStorage.getItem("epE"));
    stats.maxEp = Number(localStorage.getItem("maxEpE"));
    stats.tempEp = Number(localStorage.getItem("tempEpE"));
    stats.stamina = Number(localStorage.getItem("staminaE"));
    stats.maxStamina = Number(localStorage.getItem("maxStaminaE"));
    stats.tempStamina = Number(localStorage.getItem("tempStaminaE"));
    stats.mana = Number(localStorage.getItem("manaE"));
    stats.maxMana = Number(localStorage.getItem("maxManaE"));
    stats.tempMana = Number(localStorage.getItem("tempManaE"));
    stats.block = Number(localStorage.getItem("blockE"));
    stats.ward = Number(localStorage.getItem("wardE"));
    stats.indomitable = Number(localStorage.getItem("indomitableE"));
    stats.resImpact = Number(localStorage.getItem("resImpactE"));
    stats.resFire = Number(localStorage.getItem("resFireE"));
    stats.resFrost = Number(localStorage.getItem("resFrostE"));
    stats.resStorm = Number(localStorage.getItem("resStormE"));
    stats.resAcid = Number(localStorage.getItem("resAcidE"));
    stats.resPoison = Number(localStorage.getItem("resPoisonE"));
    stats.resFlux = Number(localStorage.getItem("resFluxE"));
    stats.resChaos = Number(localStorage.getItem("resChaosE"));
    stats.resHoly = Number(localStorage.getItem("resHolyE"));
    stats.resUnholy = Number(localStorage.getItem("resUnholyE"));
    stats.braceBlock = Number(localStorage.getItem("braceBlockE"));
    stats.braceWard = Number(localStorage.getItem("braceWardE"));
    populateStats();
}

loadStats();
populateStats();
